/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Apple Design System Colors
        'apple-black': '#000000',
        'apple-gray': '#f5f5f7',
        'apple-ink': '#1d1d1f',
        'apple-blue': '#0071e3',
        'apple-blue-link': '#0066cc',
        'apple-blue-bright': '#2997ff',
        'apple-white': '#ffffff',
        'apple-graphite-a': '#272729',
        'apple-graphite-b': '#262629',
        'apple-graphite-c': '#28282b',
        'apple-graphite-d': '#2a2a2c',
        'apple-gray-secondary': '#6e6e73',
        'apple-border-soft': '#d2d2d7',
        'apple-border-mid': '#86868b',
        'apple-dark-gray': '#424245',
      },
      fontFamily: {
        'sf-display': ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Display', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'sf-text': ['-apple-system', 'BlinkMacSystemFont', 'SF Pro Text', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      borderRadius: {
        'apple-sm': '5px',
        'apple-md': '8px',
        'apple-lg': '12px',
        'apple-xl': '18px',
        'apple-2xl': '28px',
        'apple-pill': '980px',
      },
      fontSize: {
        'hero-xl': ['80px', { lineHeight: '1.05', letterSpacing: '-1.2px', fontWeight: '600' }],
        'hero-l': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px', fontWeight: '600' }],
        'section': ['48px', { lineHeight: '1.08', letterSpacing: '-0.144px', fontWeight: '600' }],
        'product': ['40px', { lineHeight: '1.10', fontWeight: '600' }],
        'feature': ['38px', { lineHeight: '1.21', letterSpacing: '0.152px', fontWeight: '600' }],
        'promo': ['32px', { lineHeight: '1.13', letterSpacing: '0.352px', fontWeight: '600' }],
        'card-title': ['28px', { lineHeight: '1.14', letterSpacing: '0.196px', fontWeight: '600' }],
        'utility': ['24px', { lineHeight: '1.17', letterSpacing: '0.216px', fontWeight: '600' }],
        'link-action': ['21px', { lineHeight: '1.38', letterSpacing: '0.231px', fontWeight: '600' }],
        'subhead': ['19px', { lineHeight: '1.21', letterSpacing: '0.228px', fontWeight: '600' }],
        'body': ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '400' }],
        'body-emphasis': ['17px', { lineHeight: '1.24', letterSpacing: '-0.374px', fontWeight: '600' }],
        'headline': ['24px', { lineHeight: '1.17', letterSpacing: '0.216px', fontWeight: '600' }],
        'control': ['14px', { lineHeight: '1.47', letterSpacing: '-0.224px', fontWeight: '400' }],
        'footnote': ['13px', { lineHeight: '1.38', letterSpacing: '-0.08px', fontWeight: '400' }],
        'micro': ['12px', { lineHeight: '1.33', letterSpacing: '-0.12px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
